// let p = new Promise((resolve, reject) =>{
//     let a = 1;
//     if(a === 2){
//         resolve("resolved");
//         console.log("inside resolved promises");
//     }else{
//         reject("promises rejected");
//         console.log("inside rejected promises");
//     }
// })

// p.then((message) =>{
//     console.log("inside then " + message);
// }).catch((err) =>{
//     console.log("inside catch " + err);
// })


